name: m2-coursework
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - scikit-learn
    - "transformers>=4.49.0"
    - "torch>=2.6.0"
    - "accelerate>=1.4.0"
    - tqdm
    - "numpy>=2.2.3"
    - "h5py>=3.13.0"
    - ipykernel
    - ipywidgets
    - matplotlib
    - pandas
    - wandb
    - seaborn
    - pytest
    - jupyter
    - ipykernel
    - sphinx
    - sphinx-rtd-theme
    - nbsphinx
    - myst-parser
    - sphinx-rtd-theme
    - sphinx-gallery
    - nibabel
    